### ISSUE TITLE
Uncaught KQLSyntaxError exception with bad search query

### ISSUE THREAD

**Issue by cknave** [AWeber-Imbi/imbi-ui#47]
I crashed the frontend by entering a search query with a syntax error (missing `AND`).

In the console:

```
Uncaught KQLSyntaxError: Expected ")", AND, OR, whitespace but ":" found.
(namespace:***** project_type:"*****") AND NOT archived:true
-----------------------------------^
    at Qw (ast.js:38:13)
    at p (Projects.jsx:178:11)
    at onSubmit (Projects.jsx:258:13)
    at onSubmit (Filter.jsx:19:5)
    at Object.Ye (react-dom.production.min.js:52:317)
    at Xe (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Cr (react-dom.production.min.js:100:68)
    at wr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
```

**Comment by gmr** [comment]
Another example:

```
ast.js:38 Uncaught KQLSyntaxError: Expected ")", AND, OR, whitespace but ":" found.
(NOT links.sonarqube:https://sonarqube.aweber.io*) AND NOT archived:true
--------------------------^
    at Qw (ast.js:38:13)
    at p (Projects.jsx:178:11)
    at onSubmit (Projects.jsx:258:13)
    at onSubmit (Filter.jsx:19:5)
    at Object.Ye (react-dom.production.min.js:52:317)
    at Xe (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Cr (react-dom.production.min.js:100:68)
    at wr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
 ```
 
 This should be caught and an error displayed to the user.
